blank_issues_enabled: false
contact_links:
  - name: ðŸ“– HySkript Docs
    url: https://github.com/SkriptDev/HySkript/wiki
    about: Find HySkript's docs and 100's of examples
  - name: ðŸ’» Support
    url: https://discord.gg/phpWHGU
    about: Join SkriptHub's Discord server for support (and find us in the "HySkript" channels)
